import { MasterAccount, User } from '../contexts/AuthContext';

const demoTimestamp = 'demo';

export const DEMO_MASTER_ACCOUNTS: MasterAccount[] = [
  {
    id: 'demo-master-1',
    masterId: 'master-demo',
    name: 'Demo Master',
    pin: '1234',
    companyIds: [],
    createdAt: demoTimestamp,
  },
];

export const DEMO_USERS: User[] = [
  {
    id: 'demo-planner-1',
    userId: 'planner-demo',
    name: 'Demo Planner',
    role: 'Planner',
    companyName: 'Demo Construction Co.',
    companyContactMobile: '+1 555 0101',
    supervisorName: 'Alex Rivera',
    supervisorMobile: '+1 555 0102',
    siteId: 'demo-site-1',
    siteName: 'Downtown Solar Retrofit',
    pin: '1234',
    masterAccountId: 'demo-master-1',
    createdAt: demoTimestamp,
    companyIds: [],
    disabledMenus: [],
  },
  {
    id: 'demo-supervisor-1',
    userId: 'supervisor-demo',
    name: 'Demo Supervisor',
    role: 'Supervisor',
    companyName: 'Demo Construction Co.',
    companyContactMobile: '+1 555 0103',
    supervisorName: 'Jordan Blake',
    supervisorMobile: '+1 555 0104',
    siteId: 'demo-site-1',
    siteName: 'Downtown Solar Retrofit',
    pin: '1234',
    masterAccountId: 'demo-master-1',
    createdAt: demoTimestamp,
    companyIds: [],
    disabledMenus: [],
  },
  {
    id: 'demo-admin-1',
    userId: 'admin-demo',
    name: 'Demo Admin',
    role: 'Admin',
    companyName: 'Demo Construction Co.',
    companyContactMobile: '+1 555 0105',
    supervisorName: 'Taylor Morgan',
    supervisorMobile: '+1 555 0106',
    siteId: 'demo-site-1',
    siteName: 'Downtown Solar Retrofit',
    pin: '1234',
    masterAccountId: 'demo-master-1',
    createdAt: demoTimestamp,
    companyIds: [],
    disabledMenus: [],
  },
  {
    id: 'demo-qc-1',
    userId: 'qc-demo',
    name: 'Demo Quality Control',
    role: 'QC',
    companyName: 'Demo Construction Co.',
    companyContactMobile: '+1 555 0107',
    supervisorName: 'Jordan Blake',
    supervisorMobile: '+1 555 0104',
    siteId: 'demo-site-1',
    siteName: 'Downtown Solar Retrofit',
    pin: '1234',
    masterAccountId: 'demo-master-1',
    createdAt: demoTimestamp,
    companyIds: [],
    disabledMenus: [],
  },
  {
    id: 'demo-surveyor-1',
    userId: 'surveyor-demo',
    name: 'Demo Surveyor',
    role: 'Surveyor',
    companyName: 'Demo Construction Co.',
    companyContactMobile: '+1 555 0108',
    supervisorName: 'Jordan Blake',
    supervisorMobile: '+1 555 0104',
    siteId: 'demo-site-1',
    siteName: 'Downtown Solar Retrofit',
    pin: '1234',
    masterAccountId: 'demo-master-1',
    createdAt: demoTimestamp,
    companyIds: [],
    disabledMenus: [],
  },
  {
    id: 'demo-operator-1',
    userId: 'operator-demo',
    name: 'Demo Operator',
    role: 'Operator',
    companyName: 'Demo Construction Co.',
    companyContactMobile: '+1 555 0109',
    supervisorName: 'Jordan Blake',
    supervisorMobile: '+1 555 0104',
    siteId: 'demo-site-1',
    siteName: 'Downtown Solar Retrofit',
    pin: '1234',
    masterAccountId: 'demo-master-1',
    createdAt: demoTimestamp,
    companyIds: [],
    disabledMenus: [],
  },
  {
    id: 'demo-plant-1',
    userId: 'plant-demo',
    name: 'Demo Plant Manager',
    role: 'Plant Manager',
    companyName: 'Demo Construction Co.',
    companyContactMobile: '+1 555 0110',
    supervisorName: 'Taylor Morgan',
    supervisorMobile: '+1 555 0106',
    siteId: 'demo-site-1',
    siteName: 'Downtown Solar Retrofit',
    pin: '1234',
    masterAccountId: 'demo-master-1',
    createdAt: demoTimestamp,
    companyIds: [],
    disabledMenus: [],
  },
  {
    id: 'demo-staff-manager-1',
    userId: 'staff-manager-demo',
    name: 'Demo Staff Manager',
    role: 'Staff Manager',
    companyName: 'Demo Construction Co.',
    companyContactMobile: '+1 555 0111',
    supervisorName: 'Taylor Morgan',
    supervisorMobile: '+1 555 0106',
    siteId: 'demo-site-1',
    siteName: 'Downtown Solar Retrofit',
    pin: '1234',
    masterAccountId: 'demo-master-1',
    createdAt: demoTimestamp,
    companyIds: [],
    disabledMenus: [],
  },
  {
    id: 'demo-logistics-1',
    userId: 'logistics-demo',
    name: 'Demo Logistics Manager',
    role: 'Logistics Manager',
    companyName: 'Demo Construction Co.',
    companyContactMobile: '+1 555 0112',
    supervisorName: 'Taylor Morgan',
    supervisorMobile: '+1 555 0106',
    siteId: 'demo-site-1',
    siteName: 'Downtown Solar Retrofit',
    pin: '1234',
    masterAccountId: 'demo-master-1',
    createdAt: demoTimestamp,
    companyIds: [],
    disabledMenus: [],
  },
];

export const DEMO_USER_ALIASES: Record<string, string> = {
  demo: 'planner-demo',
  planner: 'planner-demo',
  supervisor: 'supervisor-demo',
  admin: 'admin-demo',
  qc: 'qc-demo',
  surveyor: 'surveyor-demo',
  operator: 'operator-demo',
  plant: 'plant-demo',
  'plant-manager': 'plant-demo',
  plantmanager: 'plant-demo',
  staff: 'staff-manager-demo',
  'staff-manager': 'staff-manager-demo',
  staffmanager: 'staff-manager-demo',
  logistics: 'logistics-demo',
  'logistics-manager': 'logistics-demo',
  logisticsmanager: 'logistics-demo',
};

export const DEMO_MASTER_ALIASES: Record<string, string> = {
  master: 'master-demo',
  owner: 'master-demo',
};

export const DEMO_DEFAULT_PIN = '1234';
